eureka:
  instance:
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
server:  
  port: ${PORT:8083}
management:
  security:
    enabled: false  
custom:
  message: Hello, client-service-zone3!    